#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
kubectl () {
    command kubectl $*
    if [[ -z $KUBECTL_COMPLETE ]]
    then
        source <(command kubectl completion zsh)
        KUBECTL_COMPLETE=1 
    fi
}

ws() {
    if [[ $1 == gs ]]; then
        cd "$HOME/workspace/getsmarter/${@:2}"
    else
        cd "$HOME/workspace/${@:1}"
    fi
}


export PATH="/usr/local/opt/helm@2/bin:$PATH"
